### ISSUE TITLE
Data Availability

### ISSUE THREAD

**Issue by HectorM14** [ColCarroll/ridge_map#12]
It may be helpful to include information about data availability from SRTM. According to this [link](https://www2.jpl.nasa.gov/srtm/), data is not available for extreme latitudes. I've also tried locations which must be just on the edge of the demarcations shown, but they didn't work.

It might be useful to throw a warning for users if values returned from `get_elevation_data` are excessively flat.

![image](https://user-images.githubusercontent.com/23343812/57201885-b9b31200-6f53-11e9-8a0c-6a450bb6be46.png)

**Comment by ColCarroll** [comment]
Thank you for this! I tried to get Denali the other day and was confused it was not available. I will try to add this to the README (along with a better description of SRTM), but happy to merge if someone else does first.

**Comment by HectorM14** [comment]
I put in a PR with some info about the data for the README. Are you interested in warning the user about seemingly empty data, or the user can use their best judgement?

**Comment by ColCarroll** [comment]
Denali was briefly confusing, but threw a warning about "all `nan`" and gave an empty box. Thank you for the contribution!
