### ISSUE TITLE
Plot disappearing

### ISSUE THREAD

**Issue by cbrum11** [ColCarroll/ridge_map#13]
Cool project!  I must be missing something very small.  Running any of the example scripts gives the following warning followed by the plot opening and closing too quickly to see.

Any suggestions?  Thanks.

`/Library/anaconda3/lib/python3.7/site-packages/skimage/util/dtype.py:141: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))`

**Comment by ColCarroll** [comment]
ooh, i am running these in a notebook. I think if you add a `plt.show()` it will open in a window, or `plt.savefig('filename.png')` it will save as a png.

**Comment by cbrum11** [comment]
DOH!  Makes total sense.  That solves it. Thanks.
