### ISSUE TITLE
set backend like matplotlib?

### ISSUE THREAD

**Issue by quarterturn** [ColCarroll/ridge_map#22]
I tried the two-line example in the python3 interpreter and got only <matplotlib.axes._subplots.AxesSubplot object at 0x7f741264d0b8>, no plot window. What am I doing wrong?

**Comment by ColCarroll** [comment]
Ooh, the examples are set up for using a notebook (where those objects get automatically displayed). I think using 

```
import matplotlib.pyplot as plt
from ridge_map import RidgeMap

RidgeMap().plot_map()
plt.show()
```
should open up a window, or 

```python
import matplotlib.pyplot as plt
from ridge_map import RidgeMap

ax = RidgeMap().plot_map()
plt.savefig('example.png')
```
should save the output to .png. 

Let me know if that works!

**Comment by quarterturn** [comment]
Thanks, that does the trick!

**Comment by quarterturn** [comment]
Closing issue
