### ISSUE TITLE
Default font Broken

### ISSUE THREAD

**Issue by cub525** [ColCarroll/ridge_map#25]
The default font has been moved, and the current url is dropping a 404

**Comment by ColCarroll** [comment]
Maybe it is back? I see a page with a download link at https://github.com/google/fonts/blob/master/ofl/cinzel/static/Cinzel-Regular.ttf

**Comment by cub525** [comment]
yes, the link just needs to be updated, I created a pull request, but it wouldn't let me

**Comment by ColCarroll** [comment]
Wow. I didn't even see that extra `static`. Thank you for the headsup!
